# Generated by Django 5.0.1 on 2024-04-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_product_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='company',
        ),
    ]
