# Generated by Django 5.0.1 on 2024-04-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='category',
        ),
    ]
